spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/phanconglaixe
    username: spring
    password: spring
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
