spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quanlyfile
    username: spring
    password: spring
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
    resources: # Static resources
      static-locations: file:src/main/resources/static/
      cache:
        period: 0