spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_spring_web
    username: spring
    password: spring
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    username: maiquyen2403
    password: lomk dwue avzz boss
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
